<a href="https://colab.research.google.com/github/arz03/fds-lab/blob/main/fds_lab_submission_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# lab file
1. working with arrays. create array and explore numpy (shape, type of elements elements, size, dimensions)
2. perform different array slicing methods
3. creating dataframes (and its methods)

1. working with arrays. create array and explore numpy (shape, type of elements elements, size, dimensions)

In [ ]:
import numpy as np

my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Create a NumPy array

# Operations on the array
print("Shape:", my_array.shape)
print("Data type:", my_array.dtype)
print("Size:", my_array.size)
print("Number of dimensions:", my_array.ndim)


Shape: (3, 3)
Data type: int64
Size: 9
Number of dimensions: 2


2. perform different array slicing methods


In [ ]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slice the array to get the first two rows and the first two columns
print("\nSlicing the first two rows and columns:")
print(my_array[:2, :2])

# Slice the array to get the last row
print("\nSlicing the last row:")
print(my_array[-1, :])

# Slice the array to get the second column
print("\nSlicing the second column:")
print(my_array[:, 1])
# Slice with a step
print("\nSlicing with a step:")
print(my_array[::2, ::2])


Slicing the first two rows and columns:
[[1 2]
 [4 5]]

Slicing the last row:
[7 8 9]

Slicing the second column:
[2 5 8]

Slicing with a step:
[[1 3]
 [7 9]]


3. creating dataframes (and its methods)

In [ ]:
import pandas as pd
students = [
    ('Anuj',25,'Delhi',35000),
    ('Ashvin',24,'Bhopal',45000),
    ('Arjun',25,'Delhi',65000),
    ('Aditya',23,'Indore',35000),
    ('Manthan',25,'Bombay', 80000),
    ('Mayank',24,'Chennai',55000),
    ('Vyomesh',26,'Bhopal',30000)]
df = pd.DataFrame(students, columns = ['Name','Age','City','Fee'])
print(df)
print('\nselect column by index: \'City\', \'Age\', \'Fee\'')
result1 = df[['City', 'Age', 'Fee']]
print(result1)
print('\nSelecting column by index with condition : City==Bhopal')
city = df[df['City']=='Bhopal']
print(city)
print('\nChanging DF index to \'City\' with set_index() method')
df.set_index("City", inplace=True)
print(df)
print('\nSelecting rows using \'loc\' method where index = Bhopal, Bombay')
result2 = df.loc[["Bhopal","Bombay"]]
print(result2)

      Name  Age     City    Fee
0     Anuj   25    Delhi  35000
1   Ashvin   24   Bombay  45000
2    Arjun   25    Delhi  65000
3   Aditya   23   Indore  35000
4  Manthan   25   Bhopal  80000
5   Mayank   24  Chennai  55000
6  Vyomesh   26   Bhopal  30000

select column by index: 'City', 'Age', 'Salary'
      City  Age    Fee
0    Delhi   25  35000
1   Bombay   24  45000
2    Delhi   25  65000
3   Indore   23  35000
4   Bhopal   25  80000
5  Chennai   24  55000
6   Bhopal   26  30000

Selecting column by index with condition : City==Bhopal
      Name  Age    City    Fee
4  Manthan   25  Bhopal  80000
6  Vyomesh   26  Bhopal  30000

Changing DF index to 'City' with set_index() method
            Name  Age    Fee
City                        
Delhi       Anuj   25  35000
Bombay    Ashvin   24  45000
Delhi      Arjun   25  65000
Indore    Aditya   23  35000
Bhopal   Manthan   25  80000
Chennai   Mayank   24  55000
Bhopal   Vyomesh   26  30000

Selecting rows using 'loc' method where index 